Dockerfile.prod
Issue #5 
Addition of Production Docker Image to run do FIM runs on the Production machines. 
- Dockerfile.prod
=> Dev prod image

lib/agreedem.py, lib/run_by_unit.sh, lib/snap_and_clip_to_nhd.py
Fixes miscellaneous bugs and improves error handling. Resolves issue #115
- change dem no data value to -999 if 0
- checkpoints throughout FIM to finish run if no relevant stream segments are found in HUC
No change observed in FR or MS evaluation scores
=> Dev prod issues

CHANGELOG.md
This update is only changing the CHANGELOG.md to include the initial version of FIM 3
=> Modifying the CHANGELOG.md with the initial release of FIM 3

lib/add_crosswalk.py, lib/run_by_unit.sh, tests/inundation.py
Resolving errors that surfaced during AHPs library generation #201
- checks dtype of hydroTable.csv columns to resolve errors caused in inundation.py when joining to flow forecast
- exits inundation.py when all hydrotable HydroIDs are lake features
- updates path to latest AHPs site layer
=> hotfix to address AHPSs mapping errors

CHANGELOG.md, lib/check_huc_inputs.py
Move HUC lists to single folder and update check_huc_inputs.py #229 
- moved huc list to inputs/huc_lists directory and updated check_huc_inputs.py
=> Move HUC lists to single folder and update check_huc_inputs.py

CHANGELOG.md, fim_run.sh, lib/acquire_and_preprocess_inputs.py
Bug fixes to correct mismatched variable name and file path. Fixes #252 
**Changes**
- fim_run.sh: corrects variable name (#206 )
- acquire_and_preprocess_inputs.py: creates huc_lists folder and updates file path (#230 )
=> Minor bug fixes

CHANGELOG.md, tools/tools_shared_functions.py
Minor patch to `tools_shared_functions.py` where `tools_shared_functions.py` was not imported correctly.
=> [1pt] PR: Patch import in tools_shared_functions.py

CHANGELOG.md, src/output_cleanup.py
Using the -p flag wasn't retaining all desired files. Fixed output_cleanup.py. Verified it now preserves desired files.
-
-
- Fixed production whitelist in output_cleanup.py.
1.
-
-
=> [1pt] PR: Fix cleanup list. dev-cleanup-hotfix

CHANGELOG.md, tools/eval_plots.py, tools/generate_categorical_fim.py
Addresses issue #362 . Plot script will now do a check to make sure the required versions are being analyzed, if not it prints a descriptive message and continues.
These commands should now work with out error:
`python3 eval_plots.py -m /path/to/all_official_versions.csv -w /path/to/workspace -v fim_3_0_9_0_fr_c fim_3_0_15_0_fr_c -sp`
`python3 eval_plots.py -m /path/to/all_official_versions.csv -w /path/to/workspace -v fim_3_0_9_0_ms_c fim_3_0_15_0_ms_c -sp`
=> [1pt] PR Update plotting script to not error out if FR or MS are not analyzed when using spatial argument

CHANGELOG.md, README.md, fim_run.sh
Updating preprocessing and input layers sections of `Readme.md`.
=> Updating Readme

README.md
Updated the readme with information about how to access data on ESIP
=> Updated README with ESIP/AWS informaton

docs/CHANGELOG.md, tools/synthesize_test_cases.py, tools/tools_shared_variables.py
Patches a bug where only certain benchmark categories were being evaluated.
=> Evaluation patch

docs/CHANGELOG.md, tools/eval_plots.py, tools/synthesize_test_cases.py, tools/tools_shared_functions.py, tools/tools_shared_variables.py
This merge adds Probability Not Detected (PND) as a metric to the evaluation code. It also updates an argument name in `eval_plots.py` after a matplotlib update.
- `synthesize_test_cases.py`: added PND into the dictionary of searched metrics
- `tool_shared_variables.py`: added PND to the `GO_DOWN_STATS` list variable
- `tools_shared_functions.py`: added the PND calculation and inclusion into `stats_dictionary`
- `eval_plots.py`:  added automatic plotting of PND and inclusion in spatial outputs. Also updated an argument in matplotlib call (I changed `b` to `visible`) in accordance with matplotlib recommendations concerning an impending deprecation of `b`.
To test, you can open `/test_cases/metrics_library/all_official_versions.csv` and confirm that the `PND` is present.
You can also run …
=> [1pt] PR: Added Probability Not Detected (PND) to evaluation code

docs/CHANGELOG.md, src/usgs_gage_crosswalk.py, tools/adjust_rc_with_feedback.py, tools/rating_curve_comparison.py, tools/tools_shared_functions.py, tools/usgs_gage_src_adjust.py, tools/wrapper_usgs_gage_crosswalk.py
This code enhancement generates a USGS gage database that contains the USGS rating curves with stage converted to water surface elevations (above HAND datum) and flow values sampled at NWM recurrence flow intervals. The database is then used to adjust the HAND-derived synthetic rating curves to more closely align with USGS gage rating curves (hydroID catchments that contain USGS gages). Addresses #495 
- `tools/usgs_gage_src_adjust.py`: Creates a database of USGS gage locations with USGS rating curve values converted to water surface elevations (sampled at flow values corresponding to NWM recurrence flow intervals -2, 5, 10, 25, 50, 100-year values). Log files are provided in the provided `fim_dir` in a new directory - `src_optimization/`
- `tools/adjust_rc_with_feedback.py`: Updated to …
=> [2pt] PR: Adjusting SRCs using USGS rating curves

unit_tests/__example_nws_data_README.md, unit_tests/__example_nws_data_params.json, unit_tests/__example_nws_data_unittests.py, unit_tests/__template_params.json, unit_tests/__template_unittests.py
Added a couple template files to make it easier for folks to add new unit test files.
- unit_tests/__template_unittests.py
- unit_tests/__template_params.json
=> [1pt] Adding unit test templates to make it easier to create new unit tests

README.md
I updated the ReadMe to replace instances of "Cahaba" with "Inundation Mapping".
=> [1pt] PR: dev-fim3 readme updates

api/frontend/gui/requirements.txt, api/node/connector/requirements.txt
Updated Flask dependency to work with the selected version of Flask. This update has no impact on the FIM software itself, but rather just the API tool that can use the FIM software.
=> Update FIM API dependency

src/aggregate_fim_outputs.py
Added check to alert when HUC `hydrotable.csv` files don't have the correct amount of columns. Resolves #578 
- Added code to `src/aggregate_fim_outputs.py` to check all `hydrotables.csv` files for consistent columns.
1. Ran against outputs with known inconsistent columns to ensure the error checking works.
2. Ran against outputs of latest BED run to confirm if the hydrotables are now being generated consistently.
After running against the latest BED run (`fim_3_0_32_0_fr_c`), I can confirm that all hydrotables have the correct number of columns (37).
=> [8pt] PR: Hydrotable Consistency Check

config/params_template.env, docs/CHANGELOG.md, fim_run.sh, src/clip_vectors_to_wbd.py
We have identified five HUC8s that were not producing FIM outputs for large portions of the expected domain. The cause of this issue varies slightly between the HUCs but the NHD headwater points were used to address the issue for all five scenarios. Address #573 
- `fim_run.sh`: minor change to move the postgreSQL database ogr2ogr commands inside the if statement that checks if SRC spatial calibration is to be run `src_adjust_spatial="True"`
- `src/clip_vectors_to_wbd.py`: created HUC specific checks to add/remove/change NHD headwater points when performing the HUC subset process. See screenshots below for explanations for point revisions applied to each HUC
1. The changes applied only come into play when running one of the five problem HUCs; therefore, I did not run a full domain test …
=> [1pt] PR: Address missing MS reaches in DEM derived flows

docs/CHANGELOG.md
Simple removing special characters that were introduced in a recent commit.
=> [1pt] PR: Removing special characters from CHANGELOG

docs/CHANGELOG.md
Fixes minor issues in CHANGELOG.md including correcting indentation of subheadings and standardizing spacing between lines.
=> Cleanup CHANGELOG.md

docs/CHANGELOG.md, tools/inundate_nation.py
bug fix and formatting upgrades. It was also upgraded to allow for misc other inundation data such as high water data.
- `tools`
- `inundate_nation.py`:  As stated above.
- it was run in a production model against fim 4.0.9.2 at 100 yr and 2 yr as well as a new High Water dataset.
=> [1pt] PR: Inundate-nation bug fixes and some minor upgrades

docs/CHANGELOG.md
Auto-merge screwed up the CHANGELOG.
=> PR: Hotfix: Update CHANGELOG.md

docs/CHANGELOG.md, gms_run_branch.sh, tools/gms_tools/combine_crosswalk_tables.py, tools/gms_tools/make_complete_hydrotable.py
Creates a single table containing HUC (huc8), BranchID, HydroID, feature_id (and optionally LakeID) from branch-level hydroTables.csv files. Closes #722.
- `tools/gms_tools/make_complete_hydrotable.py`: reads and concatenates hydroTable.csv files, writes HydroID - feature_id crosswalk table
- `gms_run_branch.sh`: Adds `tools/gms_tools/make_complete_hydrotable.py` to post-processing
=> [1pt] PR: Create HydroID - feature_id crosswalk table

data/nld/preprocess_levee_protected_areas.py, data/preprocess_rasters.py, docs/CHANGELOG.md, src/utils/shared_functions.py
New tool with instructions of downloading levee protected areas and a tool to pre-process it, ready for FIM.
- `data`
- `nld`
- `preprocess_levee_protected_areas.py`:  as described above
- `data`
- `preprocess_rasters.py`: added deprecation note. It will eventually be replaced in it's entirety.
- `src`
- `utils`
- shared_functions.py`: a few styling adjustments.
python3 /foss_fim/data/nld/preprocess_levee_protected_areas.py -s /data/inputs/nld_vectors/LeveedArea.geojson
- passed
python3 /foss_fim/data/nld/preprocess_levee_protected_areas.py -s /data/inputs/nld_vectors/LeveedArea.geojson
- should error (overwrite)  - and did. passed
python3 /foss_fim/data/nld/preprocess_levee_protected_areas.py -s /data/inputs/nld_vectors/LeveedArea.geojson -o
- passed (checked gkpg file in qgis
python3 …
=> [1pt] Add tool to preprocess downloaded levee prot areas

docs/CHANGELOG.md, src/filter_catchments_and_add_attributes.py
Adds check for empty output_catchments in `src/filter_catchments_and_add_attributes.py` . Closes #869.
- `src/filter_catchments_and_add_attributes.py`: Checks for empty `output_catchments` and throws Exit Status: 61 if empty
```
fim_pipeline.sh -u "01100003 02030203" -n fim_4_3_5_0-branch-errors -c /foss_fim/config/params_template.env -jh 2 -jb 3 -o
```
=> [1pt] PR: Check for empty output_catchments

CITATION.cff, README.md
Updated the README.md by adding a reference to Aristizabal's recent publication. Also added an extra space in one of the reference lines.
- `README.md`
=> [1pt] PR: Update README.md with new reference and grammar correction, and update CITATION.cff

docs/CHANGELOG.md, unit_tests/README.md, unit_tests/check_unit_errors_test.py, unit_tests/clip_vectors_to_wbd_params.json, unit_tests/clip_vectors_to_wbd_test.py, unit_tests/pyproject.toml, unit_tests/usgs_gage_crosswalk_test.py
Fix existing unit tests, remove unwanted behavior in `check_unit_errors_test.py`, update `unit_tests/README.md`
Closes #883. 
- `unit_tests/`
- `README.md` : Split up headings for setting up unit tests/running unit tests & re-formatted code block.
- `check_unit_errors_test.py`: Fixed unwanted behavior of test leaving behind `sample_n.txt` files in `<run_name>/unit_errors/`
- `clip_vectors_to_wbd_params.json`: Update parameters
- `clip_vectors_to_wbd_test.py`: Update arguments
- `pyproject.toml`: Ignore RuntimeWarning, to suppress pytest failure. 
- `usgs_gage_crosswalk_test.py`: Enhance readability of arguments in `gage_crosswalk.run_crosswalk` call
All Changes are within `unit_tests/` directory and the output of `pytest unit_tests/` shows:
```
================= 25 passed, 3 skipped in …
```
=> [1pt] PR: Fix and update unit tests

docs/CHANGELOG.md, fim_pipeline.sh, fim_post_processing.sh, src/aggregate_by_huc.py, src/identify_src_bankfull.py
`aggregate_by_huc.py` was taking a long time to process. Most HUCs can aggregate their branches into one merged hydrotable.csv in just 22 seconds, but a good handful took over 2 mins and a few took over 7 mins. When multiplied by 2,138 HUCs it was super slow. Multi-proc has not been added and it now takes appx 40 mins at 80 cores. 
An error logging system was also added to track errors that may have occurred during processing. 
Covers issue [888](https://github.com/NOAA-OWP/inundation-mapping/issues/888).
- `fim_pipeline.sh` - added a duration counter at the end of processing HUCs
- `fim_post_processing.sh` - added a job limit (number of procs), did a little cleanup, and added a warning note about usage of job limits in this script, 
- `src`
- `aggregate_by_huc.py`: Added multi proc, made …
=> [1pt] PR: fix speed for agg hucs

CITATION.cff
This PR simply updates the `version` in the `CITATION.cff`. There is no need to update the Changelog in this case.
`CITATION.cff`: updated version to 4.3.11.0.
=> [1pt] PR: Update version in CITATION.cff

CITATION.cff, docs/CHANGELOG.md, tools/generate_categorical_fim_flows.py
Fixes a small bug in CatFIM script where a bracket was missing on a pandas `concat` statement. 
None.
- `/tools/generate_categorical_fim.py`: fixes `concat` statement where bracket was missing. 
None.
This has been tested at full scale and completes as expected.
=> [1pt] PR: Fixes append statement in CatFIM

README.md, docs/CHANGELOG.md
Bug fix -- update AWS S3 versions availability. Closes #929.
- 'README.md': Updates URL to list data versions available on AWS S3.
=> [1pt] PR: Bug fix for AWS S3 in README.md

README.md, docs/CHANGELOG.md
Updated the `README.md` for the following edits:
1) Include a sample folder structure to increase clarity on download pathing.
2) Update docker run command notes, which had an error in it earlier.
3) Add some notes about downloading source code in relation to folder pathing.
4) Add more details on where to get `S3 input` data and where to save it to.
5) Updated notes on options for the calibration database system.
This PR is based on [Issue 934](https://github.com/NOAA-OWP/inundation-mapping/issues/934)
`README.md`: as described above
=> [1pt] PR: Update to README.md

config/params_template.env, data/bathymetry/preprocess_bathymetry.py, docs/CHANGELOG.md, fim_post_processing.sh
This PR contains a few changes to the Bathymetry adjustment routine PR #953 
-`data/bathymetry/preprocess_bathymetry.py`: added data source column to output geopackage attribute table.
-`fim_post_processing.sh`: changed -bathy input reference location.
-`config/params_template.env`: added export to bathymetry_file
Successfully tested on 9 hucs:
```
fim_pipeline.sh -n bathy_test -u "02020006 05010006 05010009 05020003 05020005 05030101 05030106 05030201 05030202" -o -isaws -jh 2 -b 3
```
=> [1pt] PR: Bathymetry adjustment hotfix

docs/CHANGELOG.md, tools/eval_plots_stackedbar.py
This hotfix addresses some bugs introduced in the pandas upgrade.
- `/tools/eval_plots_stackedbar.py`: 2 lines were changed to work with the pandas upgrade. Added an argument for a `groupby` median call and fixed a bug with the pandas `query`. Also updated with Black compliance.
```
python /foss_fim/tools/eval_plots_stackedbar.py -m /home/rdp-user/Documents/ras2fim_calibration/ras2fim-calb-metrics.csv -w /home/rdp-user/Documents/ras2fim_calibration/ -v fim_4_3_11_0 dev-no-calb dev-usgs-calb dev-ras2fim-calb -iqr
```
=> [2pt] PR Hotfix for stacked bar Eval Plots

docs/CHANGELOG.md, src/buffer_stream_branches.py, src/burn_in_levees.py, src/generate_branch_list.py, src/mask_dem.py
Fixes incorrect `nodata` value in `src/burn_in_levees.py` that was responsible for missing branches (Exit code: 61). Also cleans up related files. Closes #975.
- `src/`
- 'buffer_stream_branches.py`: Moves script functionality into a function.
- `burn_in_levees.py`: Corrects `nodata` value. Adds context managers for reading rasters.
- `generate_branch_list.py`: Removes unused imports.
- `mask_dem.py`: Removes commented code.
Ran `fim_pipeline.sh` on 08040207. Verified that the branch 1943000001 missing in #975 was no longer missing.
=> [1pt] PR: Bugfix: Correct `nodata` value in `src/mask_dem.py`

CITATION.cff, docs/CHANGELOG.md, src/usgs_gage_unit_setup.py
Corrects a bug in `src/usgs_gage_unit_setup.py` that causes incorrect values to populate a table, generating an error in `src/usgs_gage_crosswalk.py`. Fixes #986.
- `src/usgs_gage_unit_setup.py`: Changes `self.gages.location_id.fillna(usgs_gages.nws_lid, inplace=True)` to `self.gages.location_id.fillna(self.gages.nws_lid, inplace=True)`
`src/usgs_gage_crosswalk.py` runs without error:
```
USGS Crosswalk 13080002 0
Wed Sep  6 01:39:23 UTC 2023
5 gages in branch 0
Cumulative Time = 0 min(s) and 12 sec
```
=> [1pt]: PR: Bug fix for `src/usgs_gage_unit_setup.py`

data/usgs/preprocess_ahps_usgs.py, data/write_parquet_from_calib_pts.py, docs/CHANGELOG.md, src/add_crosswalk.py, src/bathy_src_adjust_topwidth.py, src/crosswalk_nwm_demDerived.py, src/derive_level_paths.py, src/finalize_srcs.py, src/identify_src_bankfull.py, src/split_flows.py, src/src_adjust_usgs_rating.py, src/src_roughness_optimization.py, src/stream_branches.py, src/subdiv_chan_obank_src.py, src/subset_catch_list_by_branch_id.py, src/usgs_gage_unit_setup.py, src/utils/shared_functions.py, tools/adjust_rc_with_feedback.py, tools/aggregate_csv_files.py, tools/combine_crosswalk_tables.py, tools/inundation.py, tools/make_boxes_from_bounds.py, tools/mosaic_inundation.py, tools/plots.py, tools/rating_curve_comparison.py, tools/vary_mannings_n_composite.py
Resolves the causes of two warnings in pandas and geopandas: (1) `FutureWarning` from taking the `int()` of single-length Series and (2) `SettingWithCopyWarning` resulting from the use of `inplace=True`.
Note: This is an update of PR #954, updated to reflect the integration of PR #988. Fixes #943, resolves #947, and closes #954.
Removed `inplace=True` from
- `data/`
- `usgs/preprocess_ahps_usgs.py`
- `write_parquet_from_calib_pts.py`
- `src/`
- `add_crosswalk.py`
- `bathy_src_adjust_topwidth.py`
- `clip_vectors_to_wbd.py`
- `crosswalk_nwm_demDerived.py`
- `derive_level_paths.py`
- `finalize_srcs.py`
- `identify_src_bankfull.py`
- `src_adjust_usgs_rating.py`
- `src_roughness_optimization.py`
- `stream_branches.py`
- `subdiv_chan_obank_src.py`
- `subset_catch_list_by_branch_id.py`
- …
=> [1pt] PR: Fix pandas and geopandas warnings

README.md
Changed a the README.md to change details on how to download from ESIP. The system has moved away from using the `--no-sign-request` and back to the previous system of using the `--requester-pays` tag.
Closes #982
=> [1pt] PR: Update README.md for ESIP download details

docs/CHANGELOG.md, src/stream_branches.py
Fixes an error related to reindexing in `StreamNetwork.drop()`. Closes #995.
- `src/stream_branches.py`: Fixes reindexing error.
Successfully tested on HUCs 01020004, 01050001, and 02020002 that previously failed in #995. Also tested on 12040101 to make sure changes didn't introduce new errors.
=> [1pt] PR: Bug fix for reindexing error

.pre-commit-config.yaml, docs/CHANGELOG.md, pyproject.toml, src/add_crosswalk.py, src/bathy_src_adjust_topwidth.py, src/bathymetric_adjustment.py, src/identify_src_bankfull.py, src/src_roughness_optimization.py, tools/vary_mannings_n_composite.py
As part of an earlier debugging process, tests were done excluding certain files from the `black` formatter. 
This PR removes the holdover exclude lists, as well as adheres recent changes to the  `black` formatter.
- `.pre-commit-config.yaml`
- `pyproject.toml`
- `src/add_crosswalk.py`
- `src/bathy_src_adjust_topwidth.py`
- `src/bathymetric_adjustment.py`
- `src/identify_src_bankfull.py`
- `src/src_roughness_optimization.py`
- `tools/vary_mannings_n_composite.py`
- 
Ran `fim_pipeline.sh` on HUC 02030105 and issued the hash_compare.py script to validate. No difference in hashes was observed.
_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your …
=> [1 pt]PR: Remove black exclude list

data/usgs/acquire_and_preprocess_3dep_dems.py, docs/CHANGELOG.md, src/utils/shared_validators.py
Upgrade our acquire 3Dep DEMs script to pull down South Alaska HUCS with its own CRS.
The previous set of DEMs run for FIM and it's related vrt already included all of Alaska, and those have not been re-run. FIM code will be updated in the near future to detect if the HUC starts with a `19` with slight different logic, so it can preserve the CRS of EPSG:3338 all the way to final FIM outputs.  See [792 ](https://github.com/NOAA-OWP/inundation-mapping/issues/792)for new integration into FIM.
New DEMs are required for: HUC8s: 19020202, 19020301, 19020602, 19020203, 19020302, 19020800, 19020201, 19020104, 19020601, 19020401, 19020103, 19020402, 19020505, 19020503, 19020504, 19020102, 19020101, 19020502, 19020501
A new vrt for the new South Alaska DEMs was also run with no changes required. …
=> [1pt] PR: Add acquire for South Alaska and download them

docs/CHANGELOG.md, src/bash_variables.env
The alpha test for v4.4.8.1 came back with a large degradation in skill and we noticed that the global manning's roughness file was changed in v4.4.7.1 - likely in error.
- `src/bash_variables.env`: changed the global roughness file to `vmann_input_file=${inputsDir}/rating_curve/variable_roughness/mannings_global_06_12.csv`
=> [2pt] PR: Hotfix for a switched global manning file

docs/CHANGELOG.md, src/bathymetric_adjustment.py
Fixes bug in bathymetric adjustment where `mask` is used with `geopandas.read_file`. The solution is to force `read_file` to use `fiona` instead of `pyogrio`. Closes #1079.
`src/bathymetric_adjustment.py`: Use `engine=fiona` instead of default `pyogrio` to use `mask=` with `geopandas.read_file`
Ran `fim_post_processing.sh` with error resolved.
=> [1pt] PR: pyogrio bug fix

docs/CHANGELOG.md, src/mask_dem.py
Fixes bug where levee-protected areas were not being masked from branch 0 DEMs. Closes #1085.
`src/mask_dem.py`: Corrects indentation preventing masked branch 0 from overwriting existing DEM.
DEM and inundation are correct after the bug fix. Tested on HUC 05040006.
=> [1pt] PR: Fix bug in levee masking in branch 0

docs/CHANGELOG.md, src/bathy_src_adjust_topwidth.py, src/identify_src_bankfull.py, src/subdiv_chan_obank_src.py, src/utils/shared_functions.py, tools/vary_mannings_n_composite.py
Bug fix for error when reading the subfolders of a directory using `listdir()` where files exist that start with an 8-digit number that are later interpreted as directories.
Fixes #1116.
The following files were modified to use `listdir()` to read only directories instead of both directories and files:
- `src/`
- `bathy_src_adjust_topwidth.py`, `identify_src_bankfull.py`, `subdiv_chan_obank_src.py`, `utils/shared_functions.py`
- `tools/vary_mannings_n_composite.py`
1. Reproduced bug
2. Implemented fix
3.  Ran `fim_post_processing.sh` without errors
=> [1pt] PR: Bug fix to prevent `listdir()` from returning filenames

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Updated some key `pre-commit` notes in the `contribute.md` file. Also added a new `deployment notes` section to the PR template.
- `PULL_REQUEST_TEMPLATE.md` \ `CONTRIBUTING.md`: as described
=> 1pt [PR] Add pre-commit and deploy notes

docs/CHANGELOG.md, src/bash_variables.env, src/run_by_branch.sh, src/run_unit_wb.sh, src/usgs_gage_crosswalk.py, src/usgs_gage_unit_setup.py
Updates USGS gage processing to use the correct projection (determined by whether the HUC is in Alaska or not). 
- `src/run_by_branch.sh`: Added `huc_CRS` as an input argument for `usgs_gage_crosswalk.py`
- `src/run_unit_wb.sh`: Added `huc_CRS` as an input argument for `usgs_gage_unit_setup.py` and `usgs_gage_crosswalk.py`
- `src/usgs_gage_crosswalk.py`: Added `huc_CRS` as an input argument for the `run_crosswalk()` function and added re-projection steps wherever new data is being read in so that the files are able to be properly merged.
- `src/usgs_gage_unit_setup.py`: Added `huc_CRS` as an input argument for the `Gage2Branch()` crosswalking class. 
Tested on 129040101 (CONUS) and 19020301 (Alaska). Before these changes, 12434 gages were found in 12040101 and 0 gages were found in …
=> [1pt] PR: Add CRS handling to USGS gage processing

config/deny_branch_zero.lst, config/deny_branches.lst, data/bridges/pull_osm_bridges.py, docs/CHANGELOG.md, fim_post_processing.sh, src/aggregate_by_huc.py, src/delineate_hydros_and_produce_HAND.sh, src/heal_bridges_osm.py
The main goal of this PR is to create bridge point data that be used as a service in HydroVIS. Since every branch processes bridges separately, it's possible to inundate a bridge from more than just the feature_id it crosses. To reflect this, the `osm_bridge_centroids.gpkg` now found in HUC directories will have coincident points - one that is inundated from the reach it crosses and the other a backwater-influenced point indicated by the `is_backwater` field.
- ` src/`
- `aggregate_by_huc.py`: Added the aggregation steps for bridge centroids; aggregation includes using SRCs to lookup flow values for each bridge, filtering out coincident points that have the same assigned feature_ids and higher overtopping flow, and assigning select points as backwater-influenced.
- ` …
=> [1pt] PR: Bridge inundation points

config/deny_branch_zero.lst, config/deny_branches.lst, docs/CHANGELOG.md, fim_post_processing.sh, src/update_htable_src.py
With this PR we can run `post_processing.sh` multiple times on a processed batch without any concerns that it may change the hydroTable or src_full_crosswalked files.
This PR addresses #1141 issue,. Previously rerunning `post_processing.sh` changed one column of hydroTable and many columns of src_full_crosswalked. 
- `src/update_htable_src.py`
-  `config/deny_branch_zero.lst`
-  `config/deny_branches.lst`
-  `fim_post_processing.sh`
=> [3pt] PR: Updating hydroTable and src _full_crosswalked

docs/CHANGELOG.md, src/add_crosswalk.py, src/bathymetric_adjustment.py, src/src_roughness_optimization.py
Changes non-fatal `ERROR` messages to `WARNINGS` to avoid triggering being logged as errors (#1169). Closes #1215.
- `src/`
- `bathymetric_adjustment.py`: Changes `WARNING` to `ERROR` in Exception
- `src_roughness_optimization.py`: Changes `ERROR` messages to `WARNING`
Ran `fim_pipeline.sh` on the HUCs in #1215.
=> [1pt] PR: Change error messages to warnings

docs/CHANGELOG.md, src/derive_level_paths.py, src/run_unit_wb.sh, src/stream_branches.py
This PR fixes bugs from `hand_4_5_10_0`, which failed to run for Alaska HUCs and HUC `02030201`. It modifies scripts to use two different DEM paths: one for Alaska and one for the CONUS.
- `src/derive_level_paths.py`
- `src/stream_branches.py`
- `src/run_unit_wb.sh`
=> [1pt] PR: Fix bugs from hand_4_5_10_0

docs/CHANGELOG.md, src/aggregate_by_huc.py, src/bash_variables.env, src/stream_branches.py
Bug fixes to address issues during `fim_pipeline.sh`. Fixes #1317 and fixes #1319 and fixes #1324.
- `src/`
- `aggregate_by_huc.py`: Fix `pyogrio` field error.
- `stream_branches.py`: Remove `bids_temp` and fix index.
Ran `fim_pipeline.sh` on 01080102, 03100204, and 065080102 without errors.
=> [1pt] PR: Fix merge conflict bugs

config/deny_branch_zero.lst, config/deny_branches.lst, config/deny_unit.lst, data/bathymetry/preprocess_bathymetry.py, docs/CHANGELOG.md
This PR updates deny lists to avoid saving unnecessary files.
I also added  PR #1260 (changes to `data/bathymetry/preprocess_bathymetry.py` ) to this PR.
- `config/deny_branch_zero.lst`
- `config/deny_branches.lst`
- `config/deny_unit.lst`
- `data/bathymetry/preprocess_bathymetry.py`
`fim_pipeline`, `inundate_mosaic_wrapper.py`, and post processing were ran successfully for huc `02070001`. 
=> [1pt] PR: Updating deny lists

docs/CHANGELOG.md, src/duration_system.py
This PR prevents the removal of the processing duration text file from each HUC to aid in debugging. This tries to fix #1458.
`src/duration_system.py` Avoids the removal of the HUC processing duration file
=> [1pt] PR: Debugging HUC processing duration system
