NOAA-OWP/inundation-mapping

lib/time_and_tee_run_by_unit.sh
Issue #6 
Using the internal bash variable `PIPESTATUS` (described [here](https://www.shellscript.sh/tips/pipestatus/)) the GNU Parallel can now properly detect exit codes in the run_by_unit scripts and reports them correctly in the `logs/summary.log`
- added exit command to `lib/time_and_tee_run_by_unit.sh`
=> Dev Exit Codes

lib/snap_and_clip_to_nhd.py, lib/split_flows.py, tests/inundation.py
This feature branch includes modifications to identify stream segments that overlap NWM lake areas. Our current HAND-FIM methodology and topography data can not adequately capture lake inundation features (i.e. we don’t have lake bathy), so this modification removes inundation output for all catchments that overlap with lake areas. FIM 2.3.3 removed most lake areas from the output inundation raster; therefore this change is also needed to ensure a fair comparison when examining the FIM2 vs. FIM3  #metrics. Resolve issue #106 
- Added code to loop through the NWM lakes multipolygon and remove any holes/islands polygon features (only keeping exterior polygons) and then overwrite the nwm_lakes_proj_subset.gpkg file for later use
- Added code to create a new lakes_buffer feature (20-meter …
=> Dev remove lakefim

lib/snap_and_clip_to_nhd.py
Hotfix for unnecessary delete function from lakefim dev branch 
- removed delete function causing error when feature does not exist
- `if` function already accounts for need to ignore lake feature input
=> Hotfix for unnessesary lake poly delete

config/params_calibrated.env, config/params_template.env, lib/run_by_unit.sh, lib/snap_and_clip_to_nhd.py, lib/split_flows.py, tests/aggregate_metrics.py, tests/synthesize_test_cases.py
Currently producing unwanted inundation outputs over ocean water areas. This is primarily due to the NHD DEM extent extending into the ocean. This feature branch uses a ocean/sea polygon to clip the REM output in run_by_unit.sh. 
Addresses issue #16
Addresses issue #124 
Download the water polygons layer from OpenStreetMap database
Optional: clip to US domain to reduce file size
Data in input directory here: /inputs/landsea/
Mask the landsea polygon to HUC wbd_buffer domain
New steps:
gdal_raster → rasterize the landsea_subset features (value = $ndv for water pixels & 1 for everywhere else)
gdal_calc → multiply existing rem_zeroed_masked.tif by new landsea_subset.tif to keep only land pixels
This overwrites the rem_zero_mask.tif (includes the previous catchment mask)
Added the lake buffer …
=> [1pt] PR: Remove ocean FIM 

README.md, config/params_calibrated.env, lib/acquire_and_preprocess_inputs.py, lib/aggregate_vector_inputs.py, lib/run_by_unit.sh
Update preprocessing scripts and remove incomplete output folders.
- #39 
- #138
- partial resolution of #118 
- added 20+ HUC4s to inputs and updated all HUCs to latest version
- updates params_calibrated.env parameters
- run_by_unit.sh now removes HUC folders that do not produce FIMs
- aggregate_vector_inputs.py merges 'FCode' attribute from NHDPlus HR Flowline layer with NHDPlusBurnLineEvent layer
- acquire_and_preprocess_inputs.py extracts new vector layers (NHDFlowline, NHDPlusLandSea, and NHDPlusBurnWaterbody) and limits included HUC lists to HUCs that contain stream segments
=> Updates to preprocessing scripts and remove incomplete output folders

fim_run.sh, lib/output_cleanup.py, lib/run_by_unit.sh
Added a module to run at the end of `run_by_unit.sh` that will handle any whitelisting and post-processing of the output files at the HUC level.
- Added `output_cleanup` module
- Implemented the new `output_cleanup` module at the end of `run_by_unit.sh`
- Wired up new argument flags in `fim_run.sh` for managing whether or not a run is for production or Viz
Resolves #88 #94 and #111
=> [1pt] Added cleanup module for production runs and viz post-processing

lib/utils/archive_cleanup.py
This PR does not need any reviewing, as I am simply commiting the script that was used to address issue #146 
This script will traverse existing fim output at the path provided, and delete all files except the ones specified in the whitelist.
=> [1pt] Script used for cleaning up previous_fim archives

lib/output_cleanup.py
When extracting the feature_ids from the `hydroTable.csv` and adding them to the `src.json`, as per Viz's output requirements, there was an issue with HydroIDs having leading zeros in the `hydroTable.csv`, but not in the `src.json`.
This was fixed by stripping the leading zeros from the HydroIDs in the `hydroTable.csv` when comparing them to the `src.json`.
With this fixed, when using the `-v` parameter, the `rating_curves_<HUD_ID>.json` should now correctly have the `nwm_feature_id` property added to each HydroID.
This fix only affects the `-v` post-processing parameter and does not affect any metrics regarding the fim output.
Some good test hucs that have HydroIDs with leading zeros are:
- 030201
- 060101
- 080402
=> Fixed issue with leading zeros in Viz Post Processing

lib/run_by_unit.sh, lib/split_flows.py
Fixes non-zero exit statuses for Great Lakes, HI, and PR #159
- adds a catch in split_flows.py to identify HUCs with no dem derived streams (Lake HUCs)
-  reprojected HI and PR rasters to `USA_Contiguous_Albers_Equal_Area_Conic_USGS_version`
- removed 04260000, 04280002, and 0426 from included HUC lists
- Opened ticket #168 to provide a more long term solution to raster projection. This will not be included in FIM v3.0
=> PR: Error handling for empty stream network in coastal/lake hucs

lib/run_by_unit.sh, lib/snap_and_clip_to_nhd.py
Some of the raw NHDPlus DEMs in the Great Lakes region (e.g. 0402-0411) use large positive values to designate no data pixels (e.g. 65535). This causes issues in the gdal_calc formula used in the REM zeroed step. Incorporated previous fix for this issue from [commit 7e6339](https://github.com/NOAA-OWP/cahaba/commit/7e6339c27ef68b683b24ea8411c0016521aa29d1?branch=7e6339c27ef68b683b24ea8411c0016521aa29d1&diff=split). Future consideration: may want to set up a more robust catch in run_by_unit.sh or in the preprocessing workflow to reassign ndv to avoid potential issues with masking positive values.
Resolves issue #160  
Use a Great Lakes water body polygon to mask REM for HUC=04. Using gl_water_polygon.gpkg input. Applies the same methods as coastal/ocean masking. If statement checks if …
=> [1pt] PR: Fix for >0 no data values & masking Great Lakes water bodies

CHANGELOG.md, lib/run_by_unit.sh
Previous configuration for the gdal_rasterize step did not assign a nodata value when converting levee lines to a raster. This was not an issue for any of the hucs that use a large negative value to denote nodata (inherited from elev_cm.tif). However, some hucs (Great Lakes region) are formatted as 16-bit unsigned integers and use a value of 65535 to assign nodata grid values. This led to issues in the “burn levees into dem” step when performing the gdal_calc maximum function → dem_meters.tif.
Solution:
- Initialize the nld_rasterized_elev.tif using a value of -9999. All grid values contain valid levee elevation values or -9999.
- Revised the “burn levees into dem” gdal_calc equation → `-calc="maximum(A,((B>-9999)*0.3048))"`
- This revised equation ignores all nld_rasterized_elev.tif …
=> Hotfix for addressing ndv in rasterized levee lines

CHANGELOG.md, lib/aggregate_fim_outputs.py, lib/output_cleanup.py
Addresses issue when running on HUC6 scale.
- src should be fixed and slightly smaller by removing whitespace
- rasters are about the same size as running fim as huc6 (compressed and tiled; aggregated are slightly larger)
- naming convention and feature id attribute are only added to the aggregated hucs (this bullet and the next one assume that Viz will not use the huc8 layer outputs)
- HydroIDs are different for huc6 vs aggregated huc8s mostly due to forced split at huc boundaries (so long we use consistent workflow it shouldn't matter)
- known issue where sometimes an incoming stream is not included in the final selection (#238) will affect aggregate outputs
=> [1pt] PR: hotfix to aggregate script

CHANGELOG.md, lib/add_crosswalk.py, lib/rem.py
The current dev is exporting the HAND thalweg reference elevation values for each pixel catchment (hand_ref_elev_table.csv) as well as the median thalweg elevation value for each hydroid segment (demDerived_reaches_split_filtered_addedAttributes_crosswalked.gpkg). These outputs provide the elevation datum for each of the synthetic rating curves. This feature branch exports the median thalweg elevation values as a new attribute in the hydroTable.csv to help facilitate future rating curve comparisons. This address #268.
- add_crosswalk.py: included "Median_Thal_Elev_m" variable outputs to hydroTable.csv
- rem.py: Renamed hydroid attribute to "Median" in case we want to include other statistics in the future (e.g. min, max, range etc.)
=> Adding HAND SRC datum elev values to hydroTable.csv output

CHANGELOG.md, tools/eval_plots.py
Spatial option of eval_plots.py was not correctly updated to reflect new data requirements. Simplified user experience in running spatial option by removing required file inputs. Address #335
Spatial option argument in eval_plots.py doesn't require user input file. Instead it generates required spatial data on the fly or uses existing file paths specified in the .env file. Outputs two spatial files with metrics populated in attribute table. A point layer for ahps sites and a polygon layer for ble.
Modification to how eval_plots.py reads the metrics csv as it now preserves leading zeros in HUCs.
An example run is:
```python3 eval_plots.py -m /path/to/metrics/csv -w /path/to/output/workspace -v fim_3_0_9_0_ -sp```
=> [1pt] Update spatial option when performing eval plots (Dev plots spatial)

CHANGELOG.md, fim_run.sh, src/clip_vectors_to_wbd.py, src/run_by_unit.sh
Remove Great Lakes from wbd buffer. Resolves issue #374
-The `gl_water_polygons.gpkg` layer is used to mask out Great Lakes boundaries and remove NHDPlus HR coastline segments. These segments are causing issues later in `run_by_unit.sh` and unnecessarily increasing total processing time.
The work done on this feature branch is mostly recycled from @RyanSpies-NOAA's feature branch `dev-ocean-mask-dem`.
Resolves non-zero exit codes for MS Great Lakes HUCs. No errors with FR/MS non-Great Lakes HUCS
FIM v3.0.15.9 MS streams for HUC 04040002
MS streams and catchments for HUC 04040002 with hotfix
Geopandas (Shapely) buffer doesn't have the same precision as GDAL so there is a slight difference in the WBD buffer layer geometries. The buffer is set to 5000 m and should be well beyond the HUC …
=> PR: Remove Great Lakes from wbd buffer

CHANGELOG.md, api/node/connector/requirements.txt
The current version of Eventlet used in the Connector module of the FIM API is outdated and vulnerable. This update bumps the version to the patched version.
=> Updated Eventlet package to 0.31.0 to patch a vulnerability

CHANGELOG.md, tools/eval_plots.py, tools/preprocess_ahps_nws.py, tools/preprocess_ahps_usgs.py, tools/run_test_case.py, tools/tools_shared_variables.py
Collection of fixes and enhancements:
run_test_case.py --> comment out return statement that was causing inundation.py to skip over certain sites
AHPS preprocessing scripts --> update edge case scenarios/workarounds and update output filenames
eval_plots.py --> Pull the bad_sites list and the query used to filter out ahps sites to discard into the tools_shared_variables.py
These address tickets #381, #369, #326, #385, #377
- Return statement in run_test_case
- Edits to custom workarounds for preprocessing ahps data
- Move the list of bad sites and the query used to filter out bad ahps locations to tools_shared_variables.py
1. To test you can run synthesize test cases, there should be "minor","moderate","major" subfolders in 02030103
2. Run eval_plots.py and it will defer to the …
=> [1pt] Bug fixes in preprocessing and run_test_case.py and update eval_plots (Dev-preprocess-ahps-fix)

CHANGELOG.md, fim_run.sh, tools/generate_nws_lid.py
The nws_lid layer is_headwater field incorrectly attributed if an ahps location was immediately downstream of an actual headwater point.  This has been corrected and it appears to affect 35 of 4,000+ sites. This addresses issue #383 and issue #397.
- Fix incorrect classification of headwater status for some sites in the nws_lid.gpkg layer.
1. run the "generate_nws_lid.py" script
LCAT2 is not assigned as a headwater (red dots)
WOBT2 not assigned as a headwater (red dots)
EMIU1 is correctly assigned as headwater (red dots) and RBCU1, RBRU1, CCSU1 are correctly classified as not_headwaters.
=> [8pt] PR: Correct headwater assignment nws_lid layer

CHANGELOG.md, src/clip_vectors_to_wbd.py
After reviewing the outputs of the last release I noticed that there needed to be a checkpoint in `clip_vectors_to_wbd.py` to make sure that the HUC contained NWM stream segments. This applies mostly to the MS extent where there is not necessarily NWM forecasting in every HUC8. 
There should be no change to the outputs from this checkpoint. 
In addition several more HUC8s have been added to the MS extent list providing complete coverage of the MS NWM domain.
=> PR: Adding line to check for NWM stream segments within HUC boundaries

docs/CHANGELOG.md, src/bathy_rc_adjust.py
This hotfix renames the BARC modified variables in src_full_crosswalked.csv to replace the original variables. The default/original variables are renamed with "orig_" prefix as outlined below. This change is needed to ensure downstream uses of the src_full_crosswalked.csv are able to reference the authoritative version of the channel geometry variables (i.e. BARC-adjust where available).
- Discharge (m3s-1) --> orig_Discharge (m3s-1)
- XS Area (m2) --> orig_XS Area (m2)
- Volume (m3) --> orig_Volume (m3)
- WetArea (m2) --> orig_WetArea (m2)
- HydraulicRadius (m) --> orig_HydraulicRadius (m)
- SA_div --> SA_div_flag
No testing needed. These changes should not have any impact on the output FIM. 
Below: list of all src_full_crosswalked.csv variables
=> Hotfix: Rename BARC variables

api/node/updater/updater.py, docs/CHANGELOG.md
Change API for release runs to use `params_template` instead of `params_calibrated`
-`api/node/updater/updater.py`: Changed `params_calibrated.env` to `params_template.env`
=> [1pt] PR: Patch updater.py after BARC merge

Pipfile, Pipfile.lock, docs/CHANGELOG.md
Updated `Pipfile` to use a specific version of `pyproj` as the newer version of `pyproj` was throwing projection issues in the `synthesize_test_cases.py` script.
This shows no changes on the hydrological outputs of fim_run.
Docker image `foss-fim:dev_pyproj_downgrade` has been created for testing purposes for the different `pyproj` version in this PR.
Addresses issue #483
=> [1pt] Update pip package to fix projection issue

docs/CHANGELOG.md, tools/rating_curve_comparison.py, tools/rating_curve_get_usgs_curves.py, tools/tools_shared_functions.py
This merge adds the functionality to create a geopackage with a point layer whose attribute table includes statistical comparison between SRCs and USGS rating curves.
- `/tools/rating_curve_comparison.py`: 
- updated recurrence intervals to reflect newest 17C run: 2, 5, 10, 25, 50, 100
- added `create_static_gpkg()` function which is called when the optional `--stat_gages` option is passed and will create a GPKG that joins a USGS gage dataset with the Sierra Test statistics
- `/tools/rating_curve_get_usgs_gages.py`: bug fixes and added simple progress indicator for gage requests and metadata processing
- `/tools/tools_shared_functions.py`: added `requests_get_with_retry()` function that is a wrapper for the requests to API calls that will retry and wait if the response is throttled
To …
=> [1pt] PR: Adds ability to create a GPKG with joined rating curve comparison statistics

docs/CHANGELOG.md, src/run_by_unit.sh, src/usgs_gage_crosswalk.py
This pull request adds an additional feature_id attribute associated with USGS gage locations (feature_id obtained from the WRDS API) output in the `usgs_gage_crosswalk.py`. There is also a new USGS gage query to check that gage HUC8 matches the FIM HUC when performing the gage-huc spatial query (avoids duplicating gages in multiple HUCs). Address #498 #502
- `src/run_by_unit.sh`: updated to include the HUC8 id as an input argument to `usgs_gage_crosswalk.py` when running `fim_run.sh`
- `usgs_gage_crosswalk.py`: updated to include both `feature_id` (HAND-FIM crosswalked feature_id) and `feature_id_wrds` (feature_id assoicated with USGS gage location obtained from WRDS API). Also included the `gage_distance_to_line` attribute to potentially identify issues with correlating gage locations …
=> [1pt] PR: refinements to usgs_gage_crosswalk.py

docs/CHANGELOG.md, src/aggregate_fim_outputs.py
Adding catchments and streams layers to viz post-processing outputs to resolve issue #501 
- Added `catchments_{huc6}.gpkg` and `streams_{huc6}.gpkg` to `aggregate_fim_outputs`
- Cleaned up imports and switched to `Path` library where applicable 
- Outputs are located in `fim_3_0_24_2_fim_run_ms`
=> Adding catchments and streams to aggregate outputs folder

Pipfile.lock
Updated Pillow python package in the Pipfile.lock to 9.0.0
This update showed no significant change in Fim Run runtime.
=> [3pt] Updated pillow dependency to 9.0.0

docs/CHANGELOG.md, src/output_cleanup.py
Hotfix to include the `usgs_elev_table.csv` in the -viz file cleanup within `output_cleanup.py`. This file is needed for sierra test input and corresponding rating curve evaluation services.
- `output_cleanup.py`: added `usgs_elev_table.csv` to list of whitelist files
=> Adding usgs_elev_table.csv to the -viz cleanup whitelist

docs/CHANGELOG.md, src/usgs_gage_crosswalk.py
Hotfix for usgs_gage_crosswalk.py error in Hawaiian HUCs `20020000` & `20070000`
- `src/usgs_gage_crosswalk.py`: Use `pygeos.coordinates.get_coordinates()` to get the snapped coordinates instead of converting to shapley objects to get the coordinates. Using `pygoes` ensures that any Z-values are not included in the coordinates.
=> [1pt] PR: Hotfix for usgs_gage_crosswalk.py error in Hawaiian HUCs

docs/CHANGELOG.md, unit_tests/README.md, unit_tests/clip_vectors_to_wbd_params.json, unit_tests/clip_vectors_to_wbd_unittests.py, unit_tests/gms/derive_level_paths_params.json, unit_tests/gms/derive_level_paths_unittests.py, unit_tests/unit_tests_utils.py
This is the start of a very basic unit test system. I can also be used to assist in development efforts. Over time, more python files can have unit tests files created for them. Additional unit tests within unit test files will likely also be add (especially for "fail" conditions where one wants to ensure that bad data is being handled correctly in the code.
- A new unit_tests folder which has the following:
- clip_vectors_to_wbd_params.json:  A set of default "happy path" values that are expected to pass validation for the   clip_vectors_to_wbd.py -> clip_vectors_to_wbd (function). 
- clip_vectors_to_wbd_unittests.py: A unit test file for src/clip_vectors_to_wbd.py. This file has only one test in it for happy path, but more are expected as "fail" test conditions are added later.
- …
=> [1pt] PR: Adds basic unit test capabilities

docs/CHANGELOG.md, fim_run.sh, src/output_cleanup.py, src/vary_mannings_n_composite.py, tools/wrapper_usgs_gage_crosswalk.py
Hotfix to updated `vary_mannings_n_composite.py` to use the same cleanup structure as `output_cleanup.py`. This addresses an issue with a hard-coded file delete step that was removing necessary csv files (i.e. `usgs_elev_table.csv`). Address #528 
- `fim_run.sh`: Passing `-v`, `-p`, and `-whitelist` arguments to `vary_mannings_n_composite.py`
- `src/output_cleanup.py`: Fixed an arg name in used in the output_cleanup function
- `src/vary_mannings_n_composite.py`: Replace the previous file cleanup code to call the `output_cleanup` function from `output_cleanup.py`. Upon completion of the SRC variable roughness workflow, the script will perform a file cleanup using the existing `output_cleanup.py` whitelist and removal process.
1. Tested on single huc using 1) `-p` flag 2) `-v` flag 3) …
=> [1pt] PR: Hotfix to address file cleanup in vary_mannings_n_composite.py

docs/CHANGELOG.md, tools/eval_plots.py, tools/synthesize_test_cases.py, tools/tools_shared_functions.py, tools/tools_shared_variables.py
I updated the evaluation tools to accept ras2fim test_cases. This will need to be performed for FIM4, as well. This addresses #511 and #533.
- `/tools/tools_shared_variables.py`: Added ras2fim benchmark magnitudes.
- `/tools/synthesize_test_cases.py`: Added ras2fim recognition.
- `/tools_eval_plots.py`: Included ras2fim in the test case categories to include in plotting.
- `/tools/tools_shared_functions.py`: Added a validity check before the calculation of PND.
1. Run `synthesize_test_cases.py` for a version and ensure that ras2fim metrics are in the master metrics CSV file.
2. Run `eval_plots.py` and confirm that ras2fim is included in the plots.
Alternatively, you can double check my outputs to make sure they look alright.
Master metrics CSV location: …
=> [1pt] PR: Updated evaluation code to accept ras2fim test cases

Pipfile.lock
This update should have no affect on the outputs or processing of the fim_run.sh script.
To test this update, use the new `foss-fim:dev_ipython_update` image on the dev server.
=> Updated the iPython dependency to version 8.0.1

docs/CHANGELOG.md, tools/collate_catchment_attributes.py
`collate_catchment_attributes.py` is located in tools. It is a simple script to assemble desired attributes for further study. The code loops through huc directories and pulls out static (does not change with stage) attributes by hydroid. It then links to sierra test metrics via location id and hydro id. 
-new tool to collate catchment attributes
-`/tools/collate_catchment_attributes.py`
these are the files I used to test the code, will run much faster
sierra_test = `"/data/outputs/carson_test1/sierra_test_sinuosity/usgs_gages_stats.gpkg"`
elev_link_table =`"/data/outputs/carson_test1/sierra_test/agg_usgs_elev_table.csv"`
hydrotable_directory =`"/data/outputs/carson_test1"`
`python collate_catchment_attributes.py -d "/data/outputs/carson_test1" -s …
=> [1pt] PR: Tool to collate catchment attributes

unit_tests/__example_nws_data_unittests.py, unit_tests/__template_unittests.py, unit_tests/clip_vectors_to_wbd_unittests.py, unit_tests/gms/derive_level_paths_unittests.py
A quick fix to help suppress unit test warnings. They were creating a lot of output making readability more difficult.
- Added: import warnings
- Added: warnings.simplefilter('ignore') to the top of each def setUpClass(self) method (a method that the unit test engine itself 
uses)
This fix was applied to the following files:
- unit_tests/clip_vectors_to_wbd_unittests.py
- unit_tests/__template_unittests.py
- unit_tests/__example_nws_data_unittests.py
- unit_tests/gms/derive_level_paths_unittests.py
The following actual usable unit tests were re-run:
- unit_tests/clip_vectors_to_wbd_unittests.py
- unit_tests/gms/derive_level_paths_unittests.py
Note: The branch can be deleted when completed.
=> [1pt] PR: Fix to suppress unit tests warnings

docs/CHANGELOG.md, gms_run_unit.sh, src/gms/derive_level_paths.py, src/gms/run_by_unit.sh, src/gms/stream_branches.py, unit_tests/gms/derive_level_paths_params.json, unit_tests/gms/derive_level_paths_unittests.py
By optionally including a "-s" command arg into `gms_run_unit.sh`, you can block loading any nwm stream records where the stream orders are 1 or 2.  By not including the "-s" arg, all stream orders will be loaded as gms was originally designed.
- None
- None
- `gms_run_unit.sh`:  Addition of an optional -s switch, which if included will block GMS from loading nwm streams with stream orders of 1 and 2.
- `src/gms`
- `run_by_unit.sh`:  Forwarding of optional new -s switch (dropLowStreamOrders) to 'derive_level_paths.py'.
- `derive_level_paths.py`:  Added optional -s (drop_low_stream_orders variable). When not submitted, it defaults to "False" meaning all stream orders will be included. When "True", this flag is forwarded to 'stream_branches.py' to filter the streams.
- `stream_branches.py`: …
=> [2pts] PR: New Feature to remove stream orders 1 and 2 if desired via command arg

docs/CHANGELOG.md, src/aggregate_fim_outputs.py
Hotfix to address error with mismatched HUC8 catchment attributes when aggregating/appending. Added a check to create "src_calibrated" field if it doesn't exist for a HUC prior to appending. Address #567 
- `src/aggregate_fim_outputs.py`: Added check to create "src_calibrated" field with "null" entries if the field doesn't exist for a HUC8. This address an error when appending catchment layers that have the field (HUC8 with calibration performed) with HUCs that do not have the field.
1. Confirmed fix on HUC6 170501 (prior error in MS BED run). Usage: `fim_run.sh -u "17050101 17050102 17050103 17050104" -e MS -c foss_fim/config/params_template.env -n ryan_temp/bug_fix_catch_attrib -j 4 -v`
=> [1pt] PR: Hotfix to address catchment aggregation with "src_calibrated" field

docs/CHANGELOG.md, gms_run_branch.sh, gms_run_unit.sh, src/gms/aggregate_branch_lists.py, tools/copy_test_case_folders.py, tools/find_test_case_folders.py, tools/run_test_case.py, tools/synthesize_test_cases.py
During large scale testing of GMS for `alpha testing` (synthesize_test_cases.py), some challenges were discovered. Tools and upgraded log / output tracking were required for `alpha testing` the large GMS processed folders. This was complicated by the fact that GMS output folders are likely not all in one directory or even one machine.
When alpha testing is completed, it adds a number of folders/files to a common `test_case` folder. The merging of folders and files from different FIM3 or FIM4/GMSprocessed folders is very tricky to amalgamate correctly and high risk. 
Extracting only GMS HUC (unit and branch) folders that were valid for alpha testing had a major impact on overall 
performance of `synthesize_test_cases.py`.  In order to figure out which output folders were required, one …
=> [1pt] PR: New tools and adjustments for bulk gms processing for alpha tests

docs/CHANGELOG.md, tools/eval_plots.py, tools/synthesize_test_cases.py, tools/tools_shared_functions.py, tools/tools_shared_variables.py
This hotfix includes several updates and revisions needed to fix/update the FIM4 evaluation scripts. These changes largely migrate revisions from the FIM3 evaluation code to the FIM4 evaluation code. Address #591 
- `tools/eval_plots.py`: Copied FIM3 code revisions to enable RAS2FIM evals and PND plots. Replaced deprecated parameter name for matplotlib grid()
- `tools/synthesize_test_cases.py`: Copied FIM3 code revisions to assign FR, MS, COMP resolution variable and addressed magnitude list variable for IFC eval
- `tools/tools_shared_functions.py`: Copied FIM3 code revisions to enable probability not detected (PND) metric calculation
- `tools/tools_shared_variables.py`: Updated magnitude dictionary variables for RAS2FIM evals and PND plots
1. Successfully completed a FIM4 …
=> [1pt] PR: Hotfixes and updates to FIM4 alpha eval and eval plots

config/params_template.env, docs/CHANGELOG.md, fim_run.sh, src/bathy_src_adjust_topwidth.py, src/utils/shared_variables.py, tools/copy_huc_dirs.py
This PR enables BARC to be implemented to FR flow lines to better match the MS inundation where FR & MS overlap. This PR uses an input env parameter to control which stream orders BARC is applied to for both FR & MS (currently set to SO 4-9). Address #585 
- `tools/copy_huc_dirs.py`: New utility script to copy a list of HUC fim output files from src directory to dst directory by feeding the script a list of HUC ids. This streamlines the development process when testing code modifications and performing the subsequent FIM evaluations.
- `config/params_template.env`: Changed `ignore_streamorders` parameter to use a list of stream orders that will be ignored within BARC routine
- `src/bathy_src_adjust_topwidth.py`: Revised to read a list of stream orders and then mask the BARC calculations …
=> [1pt] PR: Apply BARC for select FR streams

docs/CHANGELOG.md, tools/eval_plots.py, tools/inundation.py, tools/run_test_case.py, tools/synthesize_test_cases.py
This PR updates `synthesize_test_cases.py` with the ability to create MS, FR, and composite inundation agreement rasters and statistics all in one run. The new composited statistics are output in the same location within each test ID with the `_comp` suffix  replacing `_ms` for each dev or previous_fim run. Addresses #555.
`run_test_case.py` has also been refactored to use a `test_case` python class. This workflow has shown decreased memory usage as compared to the previous version of `run_test_case.py`.
- `tools/`
- `synthesize_test_cases.py`: Merged in `dev` branch (FIM 4) changes and re-factored to run FR, MS, and COMP `run_alpha_test` in that order (with multiprocessing).
- `run_test_case.py`: Merged in `dev` branch (FIM 4) changes and re-factored to run COMP tests after both FR and …
=> [1pt] PR: Update FIM3 alpha test to include MS/FR composite analysis

api/frontend/docker-compose-dev.yml, api/frontend/gui/requirements.txt, api/frontend/nginx-dev.conf, api/node/connector/requirements.txt, api/node/docker-compose-dev.yml
The API tool had to be stopped today due to an API tool restart yesterday for configuration issues. The API tool was having trouble restarting, so was updated with a different way to handle the flask version issue from a few weeks ago. See previous [PR 566.](https://github.com/NOAA-OWP/inundation-mapping/pull/566.)
A few other docker files were adjusted to show they are deprecated. In the NWC offices, only the "prod" versions are applicable and the "dev" versions can create some confusion. The "dev" versions do not fully work anyways.
This PR is based on issue [606](https://github.com/NOAA-OWP/inundation-mapping/issues/606). 
- `api`
- `node`
- `docker-compose-dev.yml`: Note added to the top of page saying now deprecated.
- `connector`
- `requirements.txt`: Changed some reference names …
=> [1pt] API Tool references fix

docs/CHANGELOG.md
I fixed a typo for v3.0.32.0 made on May 26, 2022, where the PR number did not match the PR hyperlink. I don't think we need to update the Changelog with a new version for this.
- `/docs/CHANGELOG.md`
=> [1pt] PR: Fix mismatch between PR number and hyperlink

docs/CHANGELOG.md, tools/generate_categorical_fim.py, tools/generate_categorical_fim_flows.py
This PR adds a new option to the `/tools/generate_categorical_fim.py` script `-a` that allows for an alternate method for producing inundation maps at the official AHPS flood categories.
This PR addresses #603.
I used FIM 3.0.32.0 for this testing. 3.0.32.0 includes calibration at USGS/NWS sites using both the available synthetic rating curves and the spatial “Alpha” benchmark data.
CatFIM A refers to the original CatFIM methodology, i.e. plugging the NWS threshold flows directly into the HAND synthetic rating curves, generating a new stage value different than the official threshold stage, and mapping it to the HAND grid 5 miles up and downstream of sites.
CatFIM B refers to the water surface elevation technique (see next slide). It determines the stage associated with a NWS threshold, …
=> [1pt] PR: CatFIM B Option (Water Surface Elevation Method)

Dockerfile, Dockerfile.prod
Docker build was failing saying that some packages such as shapely and entrypoints could not load.
Based on a similar issue found in dev-fim3 branch, all that was needed was to force the pipenv package to a newer version (2022.4.8)
See [Issue 633](https://github.com/NOAA-OWP/inundation-mapping/issues/633) for more details.
`Dockerfile` and `Dockerfile.prod`: Both had the same fix of forcing a version of 2022.4.8 during docker builds.
- A new docker image based on Dockerfile was created and tests for gms_run_unit.sh and gms_run_branch.sh were performed. A test against Dockerfile.prod was not performed but not expected to be an issue.
=> [1pt] Added version to pipenv in the Dockerfiles

docs/CHANGELOG.md, gms_run_branch.sh, src/gms/remove_error_branches.py, tools/gms_tools/inundate_gms.py
Removes branches that fail with Exit status: 61 in split_flows.py. Closes #653.
During `gms_run_branch.sh`, a new file, `remove_error_branches.py`, reads the `non_zero_exit_codes.log` to determine which branches exited with code 61: FIM_exit_codes.NO_FLOWLINES_EXIST. It then deletes the branch folder, removes the branch from `gms_inputs.csv`, and adds the branch to `gms_inputs_removed.csv`. 
- Adds `remove_error_branches.py` (called from `gms_run_branch.sh`)
- Adds `gms_inputs_original.csv` to save original `gms_inputs.csv` before pruning
- Adds `gms_inputs_removed.csv` to log branches that have been removed across all HUCs
- Deletes branch folders that fail
- Deletes branch from `gms_inputs.csv`
1. Run on two HUC8s, one with two branches that fail: 12100303 and 08080103 (two error …
=> [1pt] Prune branches that fail with Exit status: 61 in split_flows.py

src/gms/remove_error_branches.py, tools/eval_plots.py, tools/run_test_case.py, tools/synthesize_test_cases.py
Patches small bugs in the alpha test functionality.
- `src/gms/remove_error_branches.py`: Specified dtype when reading the gms_inputs.csv so HUCs keep their leading zeros.
-  `tools/`
- `eval_plots.py`: Added prettier FIM labels in the plot legend.
- `run_test_case.py`: Set remove_inputs to True in mosaic_inundation.
- `synthesize_test_cases.py`: Made sure that composite FIM 3 test cases are compiled with FIM 4 test cases.
=> [2pt] PR: Patches for FIM4 alpha test

docs/CHANGELOG.md, src/gms/derive_level_paths.py, src/gms/run_by_unit.sh, src/gms/stream_branches.py
Prunes branches in waterbodies
Recursively trims upstream and downstream ends of branches if they are associated with a lake feature, also removes branches entirely if they are completely in a waterbody. Closes #663.
- `src/gms/stream_branches.py`: added `trim_branches_in_waterbodies()` and `remove_branches_in_waterbodies()`
1. Ran `gms_run_unit.sh` and `gms_run_branch.sh` on HUCs 05130103, 06030002, 07140106, and 11100301
Colored lines: branches, dashed red lines: pruned segments, blue polygons: lakes, black border: HUC8 boundary
HUC 05130103
HUC 06030002
HUC 07140106
HUC 11100301
=> Prune branches in waterbodies

docs/CHANGELOG.md, src/gms/derive_level_paths.py, src/gms/stream_branches.py, unit_tests/gms/derive_level_paths_unittests.py
When deriving level paths using only arbolate sum, branches end up veering off the main river near the upstream HUC8 boundary because the main river has a lower arbolate sum due to being cut off at the WBD. This improvement uses stream order to override that behavior so that the branch stays on the main river. Addresses #660.
- `src/gms/`
- `derive_level_paths.py`: Added `order_` to the list of comparison_attributes in the `derive_stream_branches` method.
- `stream_branches.py`: Updated the `derive_stream_branches` method to first consider stream order when choosing which upstream segment to continue the current level path. If both upstream segment have the same order, then arbolate sum is used.
-  `unit_tests/gms/derive_level_paths_unittests.py`: Updated the import to the new class.
1. …
=> [1pt] PR: Update derive level paths to use stream order

docs/CHANGELOG.md, tools/rating_curve_comparison.py
Adds capability to produce single rating curve comparison plots for each gage. This PR is identical to #709 except this one is for FIM3.
- `tools/rating_curve_comparison.py`
- Adds `generate_single_plot()` to make a single rating curve comparison plot for each gage in a given HUC
- Adds command line switch to generate single plots
=> [1pt] Adds capability to produce single FIM3 rating curve comparison plots for each gage

docs/CHANGELOG.md, src/gms/buffer_stream_branches.py, src/gms/derive_level_paths.py, src/gms/generate_branch_list.py, src/gms/stream_branches.py
Runs branch 0 on HUCs with no other branches remaining after filtering stream orders if `drop_low_stream_orders` is used. Closes #715.
- `src/gms`
- `stream_branches.py`: adds `exclude_attribute_values()` to filter out stream orders 1&2 outside of `load_file()`
- `src/gms`
- `buffer_stream_branches.py`: adds check for `streams_file`
- `derive_level_paths.py`: checks length of `stream_network` before filtering out stream orders 1&2, then filters using `stream_network.exclude_attribute_values()`
- `generate_branch_list.py`: adds check for `stream_network_dissolved`
1. Ran `gms_run_unit.sh` and `gms_run_branch.sh` on HUCs 10060007 (no 3+ stream orders) and 12030102
=> [1pt] PR: Runs branch 0 on HUCs without other branches after stream order filtering

docs/CHANGELOG.md, src/clip_vectors_to_wbd.py, src/gms/run_by_unit.sh
Ports thalweg notch fix from FIM3 (#679: dev-fim3-fix-reverse-flow), which fixes thalweg notch created by clipping upstream ends of the stream segments to prevent the stream network from reaching the edge of the DEM and being treated as outlets when pit filling the burned DEM.
- `src/clip_vectors_to_wbd.py`: Uses a slightly smaller buffer than wbd_buffer (wbd_buffer_distance-3*[DEM cell size]) to clip stream network inside of DEM extent.
=> [1pt] PR: Port thalweg notch fix from FIM3

data/create_vrt_file.py, data/usgs/acquire_and_preprocess_3dep_dems.py, docs/CHANGELOG.md, src/gms/run_by_unit.sh
Earlier versions of the acquire_and_preprocess_3dep_dems.py did not have any buffer added when downloading HUC6 DEMs. This resulted in 1 pixel nodata gaps in the final REM outputs in some cases at HUC8 sharing a HUC6 border. Adding the param of cblend 6 to the gdalwarp command meant put a 6 extra pixels all around perimeter. Testing showed that 6 pixels was plenty sufficient as the gaps were never more than 1 pixel on borders of no-data.
- `data`
- `usgs`
- `acquire_and_preprocess_3dep_dems.py`: Added the `cblend 6` param to the gdalwarp call for when the dem is downloaded from USGS.
- `create_vrt_file.py`:  Added sample usage comment.
- `src`
- `gms`
`run_by_unit.sh`: Added a comment about gdal as it relates to run_by_unit.
Note: the new replacement inputs/3dep_dems/10m_5070/ files can / …
=> [1pt] PR: Add cblend (buffer) to acquire 3dep downloads

Pipfile, Pipfile.lock, docs/CHANGELOG.md
Due to a recent IT security scan, it was determined that Jupyter-core needed to be upgraded.
- `Pipfile` and `Pipfile.lock`:  Added a specific version of Jupyter Core that is compliant with IT.
Built a new test docker image and container with the new Pipfile and Pipfile.lock. Used gms_pipeline to validate it still processes huc's ok and turned on Jupyter hooking it to a browser and all is well.
'
Note: This fix does not require rebuilding of new Docker images, but can wait until that opportunity comes up again. However.. it needs to be merged as soon as reasonably possible.
=> [1pt] PR: Upgrade jupyter core

docs/CHANGELOG.md, src/gms/run_by_unit.sh
Skip `usgs_gage_unit_setup.py` if no level paths exist. This may happen if a HUC has no stream orders > 2. This is a bug fix for #723 for the case that the HUC also has USGS gages.
- `src/gms/run_by_unit.sh`: Adds check for `nwm_subset_streams_levelPaths.gpkg` before running `usgs_gage_unit_setup.py`
=> [1pt] PR: Skip `usgs_gage_unit_setup.py` if no level paths

config/deny_gms_branches_dev.lst, config/deny_gms_branches_prod.lst, config/deny_gms_unit_prod.lst, docs/CHANGELOG.md
Updating a few deny list files.
- `config`
- `deny_gms_branches_dev.lst`: gw_catchments_reaches_filtered_addedAttributes_{}.gpkg no longer being kept after cleanup.
- `deny_gms_branches_prod.lst`: gw_catchments_reaches_filtered_addedAttributes_{}.gpkg no longer being kept after cleanup.
- `deny_gms_unit_prod.lst`: incorrect spelling for NHPlusBurnLineEvent_subset.gpkg. It is now being removed correctly. Also added a new line for a recently new file called wbd_buffered_streams.gpkg which will be kept as output for now.
Tested a HUC and validated updates to output cleanup. No permutations of testing required.
=> [1pt] Cleanup a few deny list files

docs/CHANGELOG.md, tools/inundation.py
Bug fix for `inundation.py` ignoring nodata value and inundating masked areas in REM raster. Fixes #761
- `tools/inundation.py`: Sets depth to `0` if REM value is less than `0`
1. Ran `inundation.py` on HUC 12030109 branch 0. Verified values in QGIS (screenshot below).
2. Ran `gms_pipeline.sh` and `synthesize_test_cases.py` on HUC 12030109 without errors.
Levee-protected areas (gray, 50% transparent) are no being inundated, for example in the depth raster:
=> [1pt] PR: Bug fix: `inundation.py` ignoring nodata

docs/CHANGELOG.md, src/gms/delineate_hydros_and_produce_HAND.sh, src/gms/mask_dem.py
Masks levee-protected areas from DEM in branch 0 and two highest stream order branches to prevent slivers of inundation along the perimeter of levee-protected areas. Masking the DEM causes the same levee-protected area to be masked in the REM as well as the pixel catchments of any stream pixels in the leveed area. Closes #759 
- `src/gms/`
- `mask_dem.py`: Masks levee-protected areas from DEM in branch 0 and two highest stream order branches
- `src/gms/delineate_hydros_and_produce_HAND.sh`: Adds `src/gms/mask_dem.py`
1. Ran `src/gms/mask_dem.py` on branch 0 of HUC 12030109 to verify correct masking of DEM.
2. Ran `Inundate_gms` and `Mosaic_inundation` on HUC 12030109 to verify effect of masking DEM on REM and final inundation.
1. DEM (`dem_meters_0.tif`) with levee-protected areas masked …
=> [1pt] PR: Mask levee-protected areas from DEM

docs/CHANGELOG.md, tools/generate_categorical_fim.py, tools/generate_categorical_fim_mapping.py
This merge fixes a bug where all of the Stage-Based intervals were the same. Closes #777.
- `/tools/generate_categorical_fim.py`: Changed `stage` variable to `interval_stage` variable in `produce_stage_based_catfim_tifs` function call.
We tested this on UCS and it ran properly.
=> [1pt] PR: Bug fix to Stage-Based CatFIM

config/aws_s3_put_fim4_hydrovis_whitelist.lst, docs/CHANGELOG.md
Added crosswalk_table.csv from the root output folder as being a file push up to Hydrovis s3 bucket after FIM BED runs.
- `config`
- `aws_s3_put_fim4_hydrovis_whitelist.lst`:  Added crosswalk_table.csv to whitelist.
Did a test push of a small batch up to Hydrovis s3 bucket and confirmed the crosswalk file was there.
=> [1pt] PR: Update hydrovis S3 push whitelist

docs/CHANGELOG.md, src/clip_vectors_to_wbd.py, src/gms/run_by_unit.sh
Removes Great Lakes clipping. Unnecessary since removal of NHD datasets (PR #744). Closes #783.
- `src/`
- `clip_vectors_to_wbd.py`: Removed Great Lakes clipping section and references to Great Lakes polygon dataset.
- `gms/run_by_unit.sh`: Removed parameters for Great Lakes polygons and lake buffer size
1. `gms_pipeline.sh` produced equivalent results on the original problem HUCs (04040002 and 04060101) with Great Lakes clipping removed.
=> [1pt] PR: Remove Great Lakes clipping

docs/CHANGELOG.md, tools/gms_tools/combine_crosswalk_tables.py
Bug fix for `combine_crosswalk_tables.py` fails if only one HUC is run. Fixes #795
- `tools/gms_tools/combine_crosswalk_tables.py`: Checks length of dataframe list before concatenating
1. Successfully ran `gms_pipeline.sh -u 12030105 -c /foss_fim/config/params_template.env -j 6 -o -n dev`
=> [1pt] PR: Bug fix: combine_crosswalk_tables.py fails if only one HUC is run

docs/CHANGELOG.md, tools/pixel_counter.py, tools/test_case_by_hydro_id.py
When running tools/test_case_by_hydroid.py, it throws an error of local variable 'stats' referenced before assignment.
- `tools`
- `pixel_counter.py`: declare stats object and remove the GA_Readonly flag
- `test_case_by_hydroid_id_py`: Added more logging.
Ran the tool against fim_4_0_18_0 with success.
=> [1pt] PR: Fix error msg of stats object not referenced

docs/CHANGELOG.md, src/run_unit_wb.sh
FIM 4.2.0.0. was throwing errors for 14 HUCs that did not have any level paths. These are HUCs that have only stream orders 1 and 2 and are covered under branch zero, but no stream orders 3+ (no level paths).  This has now been changed to not throw an error but continue to process of the HUC.
- `src`
- `run_unit_wb.sh`: Test if branch_id.lst exists, which legitimately might not. Also a bit of text cleanup.
Ran fim_process_unit_wb.sh with a valid HUC and one invalid HUC to ensure the fix is correct. An invalid HUC is 01010011. Prior to the fix, the unit_errors folder would have a HUC unit log in the folder, but will not exists post fix. Pre-fix will show only partial cleanup of the branch_zero (branches/0) folder and you will specifically  notice the dem_meters_0.tif file will exist. Post …
=> [1pt] PR: Fix for missing branch_id.lst file

docs/CHANGELOG.md, src/stream_branches.py
Changes `.split()` to `os.path.splitext()` to avoid error where there are multiple periods in the path where `.split()` would return more than two items. Fixes #844.
- `src/stream_branches.py`: Changed 3 instances of `.split()` to `os.path.splitext()`
Successfully ran `fim_pipeline.sh -u 12050006 -n dev-4.3.1.0 -c /foss_fim/config/params_template.env`
=> [1pt] PR: Bug fix - Change .split() to os.path.splitext()

docs/CHANGELOG.md, tools/tools_shared_variables.py
At least one site (TRYM7) has not been getting mapped in Stage-Based CatFIM, despite having all of the acceptable accuracy codes. This was caused by a data type issue in the acceptable_coord_acc_code_list in tools_shared_variables.py having 5 as a string instead of an integer.
- `/tools/tools_shared_variables.py`: Added an integer `5` to the `acceptable_coord_acc_code_list`
1. Ran stage-based catfim for TRYN7 and confirmed that mapping is now occurring.
=> [1pt] PR: Fixed datatype issue in coord accuracy list

.github/PULL_REQUEST_TEMPLATE.md, docs/CHANGELOG.md
Simple update to the `PULL_REQUEST_TEMPLATE.md` to remove unnecessary/outdated boilerplate items,  add octothorpe (#) in front of Additions, Changes, Removals to mirror CHANGELOG.md format, and clean up the PR Checklist. 
- `docs/`  
- `PULL_REQUEST_TEMPLATE.md` - Update template to match CHANGELOG formatting, improve checklist to be applicable
n/a
=> [1pt] PR: Update PR template

docs/CHANGELOG.md, fim_process_unit_wb.sh, src/run_unit_wb.sh
outputs_cleanup.py was throwing an error saying that the HUC source directory (to be cleaned up), did not exist. This was confirmed in a couple of environments. The src path in run_unit_wb.sh was sending in the "outputs" directory and not the "fim_temp" directory. This might have been a merge issue.
The log file was moved to the unit_errors folder to validate the error, as expected.
Related to [Issue 866]([2pt] FIM 4.3.5.0 error on outputs_cleanup.py #866). 
- `src/run_unit_wb.sh`: Change the source path being submitted to `outputs_cleanup.py` from the `outputs` HUC directory to the `fim_temp` HUC directory.
- `fim_process_unit_wb.sh`: Updated the phrase "Copied temp directory" to "Moved temp directory"
Ran a simply fim pipeline for one HUC, watched the screen outputs, ensure the HUC …
=> [1pt] PR: HUC outputs not be cleaned and erroring out

Dockerfile, docs/CHANGELOG.md
Upgrades JDK in Docker image to v.17.0.9. Resolves #1029.
Note: We may still want to upgrade GDAL to a more current version than v.3.4.3 but this will require getting past the TauDEM `aread8` isssue so GDAL in the current image is still fixed at v.3.4.3.
- `Dockerfile`: Adds JDK v17 to image
Ran `fim_pipeline.sh` and `synthesize_test_cases.py` on HUCs 12040101 and 12090301 against v.4.4.7.1 with identical evaluation results.
=> [1pt] PR: Upgrade JDK to v.17

.github/PULL_REQUEST_TEMPLATE.md, docs/CHANGELOG.md, src/add_crosswalk.py, src/bash_variables.env, src/delineate_hydros_and_produce_HAND.sh, src/heal_bridges_osm.py, src/run_unit_wb.sh
Fixes two bugs discovered in v4.5.0.0:
1. `echo` missing in bash command
2. raster resolution of `dem_meters.tif` has now been explicitly set in `gdalwarp`.
Closes #1131 and closes #1148 and closes #1153.
- `src/`
- `add_crosswalk.py`: fixed stream order if max > `max_order`
- `bash_variables.env`: added `res` environment variable for default raster cell size
- `delineate_hydros_and_produce_HAND.sh`: added missing `echo`
- `heal_bridges_osm.py`: fixed raster resolution and number of rows/columns
- `run_unit_wb.sh`: added `-tr` to gdalwarp when generating `dem_meters.tif`; removed extraneous `Tcount`
Ran `fim_pipeline.sh` and verified that no errors occurred and the `dem_meters.tif` raster resolutions is exactly 10 meters.
_You may update this …
=> [1pt] PR: v4.5.0.0 bug fixes

docs/CHANGELOG.md, tools/generate_nws_lid.py
This PR addresses issue #1132 and produces an updated input dataset to replace `/dev_fim_share/foss_fim/inputs/ahps_sites/nws_lid.gpkg` with `/dev_fim_share/foss_fim/outputs/ali_nws_lid/nws_lid.gpkg`
The PR includes the following changes on `tools/generate_nws_lid.py` for updating `nws_lid.gpkg` dataset. 
In this revised version, stations only from these two groups are retrieved:
- lid stations with `rfc_forecast_point= True` 
- lid stations in `/data/inputs/ahp_sites/evaluated_ahps_sites.csv`
The lid stations in AK (Alaska), HI, and PR, with above two criteria have also been selected, as shown in the map below. In the previous version of the code, **all of lid stations** in PR and HI (regardless of meeting above two criteria), were also being retrieved. I have updated this version to …
=> [5pt] PR: Update nws_lid dataset with Alaska sites

docs/CHANGELOG.md, fim_pipeline.sh, fim_post_processing.sh, src/bash_functions.env, src/run_by_branch.sh, src/run_unit_wb.sh, src/src_adjust_ras2fim_rating.py, tools/hash_compare.py
Prior to this fix, fim_post_processing.sh took just under 4 hours to reset permissions on all files and folder under the entire run. On closer inspection, it was updating permissions for all HUC folders where were already correct. A few other folders needed to have permission updates added. This will speed that up significantly.
Also, use this opportunity to added a new note to hash_compare.py and fix an annoying duration time showing milliseconds.
- `fim_pipeline.sh`: fix duration msgs.
- `fim_post_processing.sh`:  permissions reset fix, a bit of output cleanup and fix duration msgs.
- `src`
- `bash_functions.env`: update the Calc duration to allow for a msg prefix to be added to the duration calcs. Also adjusted the duration message to show hours as well, previously only min and …
=> [1pt] PR: Change Post proc perms updates

docs/CHANGELOG.md, src/heal_bridges_osm.py
This PR resolves #1457 by ensuring that HUCs without lidar-informed bridges are properly handled. The code now checks for the availability of lidar-informed bridges, and if none exist for a given HUC, the lidar healing workflow is skipped.
- `src/heal_bridges_osm.py`  ... As described above. 
A series of runs were conducted for three HUCs (19020800, 17100305, 18090103) that previously encountered errors during the Build 4.6.0.0 run. After applying the fix, all tested runs completed successfully
=> [1pt] PR: Bug fix to handle HUCs without any lidar-informed bridges
